version: '3.9'

services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=iot_data
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin_password
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    volumes:
      - influxdb_data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_password
    volumes:
      - grafana_data:/var/lib/grafana

  python-script:
    image: python:3.9
    container_name: python-script
    volumes:
      - ./scripts:/scripts
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=XdDgvjQXTymljILun5Ellh3iAmCUv2KStpBK4qSpnS13Sw0LIAw-3UBPcFpB9x7HOfxoXvY1ZEEVtJrDHpd-bw==
      - INFLUXDB_ORG=my-org
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data:
