{
 "title": "Lab Management",
 "time": { "from": "2024-07-04T05:12:32.831Z", "to": "2024-07-06T05:12:32.831Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Lab Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lab Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lab2\")\r\n  |> range(start: -1h)  // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"lab data\" and r._field == \"temperature\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Number of People in Lab",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lab2\")\r\n  |> range(start: -1h)  // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"lab data\" and r._field == \"people\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "AQI Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lab2\")\r\n  |> range(start: -1h)  // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"lab data\" and r._field == \"aqi\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "CO2 Level",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"lab2\")\r\n  |> range(start: -1h)  // Adjust the time range as needed\r\n  |> filter(fn: (r) => r._measurement == \"lab data\" and r._field == \"co2\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "Sample In-Out Time Table",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 6, "y": 7 },
   "targets": [
    { "path": "maps" }
   ]
  }
 ]
}